config/routes.rb
Flatman::Application.routes.draw do

scope "(:locale)", locale: /en|de/ do
  root :to => 'templates#index'

  get '/about', :to => :about, controller: :public
  get '/contact', :to => :contact, controller: :public
  get '/terms', :to => :terms_and_privacy, controller: :public
  get '/welcome', :to => :welcome, controller: :public

  namespace :templates do
    get '/finances', to: :finances, as: 'finances'
    get '/flat_settings', to: :flat_settings, as: 'flat_settings'
    get '/create_resource', to: :create_resource, as: 'create_resource'
    get '/resources', to: :resources, as: 'resources'
    get '/user_settings', to: :user_settings, as: 'user_settings'
    get '/dashboard', to: :dashboard, as: 'dashboard_template'
    get '/newsfeed', to: :newsfeed, as: 'newsfeed_template'
    get '/pinboard', to: :pinboard, as: 'pinboard'
    get '/create_flat', to: :create_flat
    get '/finance_entry', to: :finance_entry, as: 'finance_entry'
    get '/bills_overview', to: :bills_overview, as: 'bills_overview'
    get '/finance_overview_mate', to: :finance_overview_mate, as: 'finance_overview_mate'
    get '/create_payment', to: :create_payment, as: 'create_payment'
  end

  namespace :api, defaults: {format: :json} do
   resources :status, only: [:index]
   resources :invite, only: [:create,:destroy]

   namespace :flat do
      get '/', to: :index
      put '/', to: :create
      post '/', to: :update
      get '/mates', to: :flat_mates
      delete '/user', to: :leave_flat
      put '/user', to: :join_flat
   end

   resources :user, only: [:index]
   post '/user/' => 'user#update'

   resources :shoppinglist, only: [:index, :create, :destroy] do
      resources :shoppingitem, only: [:create, :update, :destroy]
      delete '/delete_checked', to: :delete_checked
      delete '/was_shopping', to: :was_shopping
   end
   get '/shopping/get_most_bought_items' => 'shoppingitem#get_most_bought_items'

   resources :todo, only: [:index, :create, :destroy] do
      resources :todo_item, only: [:create, :update, :destroy]
      delete '/delete_checked', to: :delete_checked
   end

   resources :newsfeed, only: [:index, :create, :destroy]
   post '/newsfeed/comment/' => 'newsfeed#comment'

   resources :resource, only: [:index, :create, :update, :destroy] do
      resources :resourceentry, only: [:create, :destroy]
   end
   get '/resource/:resource_id/resourceentry/' => 'resourceentry#page'
   get '/resource/:resource_id/chart' => 'resource#get_chart'
   get '/resource/:resource_id/overview' => 'resource#get_overview'
   get '/resource/:resource_id' => 'resource#get_by_id'

   get '/dashboard/resource' => 'resource#dashboard'

   resources :bill, only: [:create, :update,:show, :destroy, :index]

   get '/finance/category' => 'finance#get_by_category'
   get '/finance/overviewMates' => 'finance#get_overview_mates'
   get '/finance/overviewMates/:mate_id/' => 'finance#get_overview_mate'

   post "/payment" => 'payment#create'
   delete "/payment/:id/:mate_id" => 'payment#destroy'
  end

  match 'auth/:provider/callback', to: 'session#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  get "auth/join_flat/:token", to: "session#join", as: "join" 
  match 'signout', to: 'session#destroy', as: 'signout', via: [:get, :post]
  match 'signin', to: 'session#index', as: 'signin', via: [:get, :post]

  match '/404', :to => 'errors#not_found', via: :all
  match '/500', :to => 'errors#server_error', via: :all
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="flatman">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, height=device-height,  initial-scale=1.0, user-scalable=no, user-scalable=0, maximum-scale=1"/>
    <meta property="og:description" name="description" content="<%= content_for?(:description) ? yield(:description) : t('.default_description') %>">
    <meta name="robots" content="<%= yield :robots %>">
    <meta name="author" content="Clemens Brunner, Michael Froewis">
    <meta name="google-site-verification" content="24dGcQyKurRHX8RcO9sXp5pB-LqGotGHMVUM-U3YsgU" />
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="keywords" content="flatman, wg, finanzen, finances, strom, gas, zählerstände, verwalten, manage, flatman, electricity, finances, flat, shared flat, innsbruck, austria, clemens, michael, brunner, froewis, cool, newsfeed">
    <meta http-equiv="content-language" content="de">
    <meta property="og:image" content="<%= image_path("flatman_logo_30.png")%>" />
    <meta property="og:title" content="Flatman"/>
    <meta property="og:type" content="finances" />
    <meta property="og:url" content="https://www.flatman.at" />

    <title>FlatMan<%= " » " + h(yield(:title)) if content_for?(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all"%>
    <%= csrf_meta_tags %>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body ng-controller="rootCtrl" hm-swipe-left="go_right()" hm-swipe-right="go_left()">

    <!-- loading overlay before ng-cloak -->
    <div class="splash" ng-cloak>
      <div class="loading-overlay">
        <span class="fa fa-refresh fa-spin fa-5x loading-overlay-centered"></span>
      </div>
    </div>

    <!-- loading overlay for small devices -->
    <div ng-show="isLoading()">
      <div class="visible-xs loading-overlay">
        <span class="fa fa-refresh fa-5x fa-spin loading-overlay-centered"></span>
      </div>
    </div>

    <div class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation" ng-cloak>
      <div class="container-fluid">
        <div class="navbar-header">
          <% if is_user_ready_to_go %>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <button type="button" class="btn btn-default navbar-btn pull-right visible-sm visible-xs" ng-click="reload_view()" style="margin-right:10px">
              <span class="fa fa-refresh fa-lg" ></span>
            </button>
          <%end%>
          <% if not is_user_ready_to_go and logged_in %>
            <a href="/signout" class="btn btn-default navbar-btn pull-right visible-sm visible-xs"><span class="glyphicon glyphicon-off"></span> <%=t("misc.titles.logout")%></a>
          <%end%>
          <a class="navbar-brand" href="/#/newsfeed"><%= image_tag("flatman_logo_30.png", width: 30) %> flatman</a>
        </div>
        <% if not is_user_ready_to_go and logged_in %>
        <div class="navbar-collapse collapse no-transition">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/signout"><span class="fa fa-power-off fa-fw fa-lg"></span> <%=t("misc.titles.logout")%></a></li>
          </ul>
        </div>
        <%end%>
        <% if is_user_ready_to_go %>
          <div class="navbar-collapse collapse no-transition">
            <ul class="nav navbar-nav">
              <li ng-class="{active:isActive('/newsfeed')}">
                <a href="/#/newsfeed" ><span class="fa fa-dashboard fa-fw fa-lg"></span>  <%=t(".navbar.newsfeed")%></a>
              </li>
              <li ng-class="{active:isActive('/shopping')}">
                <a href="/#/shopping"><span class="fa fa-shopping-cart fa-fw fa-lg"></span>  <%=t(".navbar.shopping")%></a>
              </li>
              <li ng-class="{active:isActive('/todo')}">
                <a href="/#/todo"><span class="fa fa-list-alt fa-fw fa-lg"></span>  <%=t(".navbar.pinboard")%></a>
              </li>
              <li ng-class="{active:isActive('/finances')}">
                <a href="/#/finances"><span class="fa fa-bitcoin fa-fw fa-lg"></span>  <%=t(".navbar.finances")%></a>
              </li>
              <li ng-class="{active:isActive('/resources')}">
                <a href="/#/resources"><span class="fa fa-globe fa-fw fa-lg"></span>  <%=t(".navbar.resources")%></a>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="flatman-navbar-item hidden-sm hidden-xs" ng-show="isLoading()">
                <a><span class="fa fa-circle-o-notch fa-spin fa-lg" ></span></a>
              </li>
              <li class="flatman-navbar-item hidden-sm hidden-xs" ng-show="!isLoading()">
                <a ng-click="reload_view()"><span class="fa fa-refresh fa-lg" ></span></a>
              </li>
              <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="fa fa-user fa-lg fa-fw"></span> <%=current_user.name%> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li ng-class="{active:isActive('/flat_settings')}">
                    <a href="/#/flat_settings"><span class="fa fa-wrench fa-fw fa-lg"></span> <%=t(".navbar.flat_settings")%></a>
                  </li>
                  <li ng-class="{active:isActive('/user_settings')}">
                    <a href="/#/user_settings"><span class="fa fa-cog fa-fw fa-lg"></span> <%=t(".navbar.user_settings")%></a>
                  </li>
                  <li class="divider"></li>
                  <li><a href="/signout"><span class="fa fa-power-off fa-fw fa-lg"></span> <%=t("misc.titles.logout")%></a></li>
                </ul>
              </li>
            </ul>
          </div> 
        <% end %>
      </div>
    </div>

    <div id="container" class="<%= content_for?(:no_container) ? "" : "container" %>" ng-cloak>
      <section>
        <% flash.each do |key,message| %>
          <div class="alert alert-<%= key.to_s %> alert-dismissable auto-fadeout">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%=message%>
          </div>
        <% end %>

        <div class="flyover flyover-top"
              ng-class="{in:Util.has_server_errors}">
          <alert ng-repeat="error in server_errors track by $index" type="error_type" close="delete_error($index)">
            <i class="fa fa-exclamation-triangle fa-lg"></i> {{error}}
          </alert>
        </div>

        <%= yield :validation %>
      </section>

      <%= yield %>
    </div>

    <div id="footer" ng-cloak>
      <div class="container">
        <p class="text-muted">
          <div class="row">
            <div class="col-md-4 col-xs-6">
              &copy; flatman <%= Time.now.year %>
              <!--<% if is_app_user? && current_user.platform == "ios"%>
                <i class="fa fa-apple"></i>
              <%end%>
              <% if is_app_user? && current_user.platform == "android"%>
                <i class="fa fa-android"></i>
              <%end%>-->
            </div>
            <div class="col-md-4 col-xs-6 text-center">
              <%= link_to_unless(I18n.locale == :en,
                      t('misc.titles.language.english'),{locale: :en},{:onclick => "this.href=this.href+'/'+window.location.hash" })%> |
              <%= link_to_unless(I18n.locale == :de,
                      t('misc.titles.language.german'),{locale: :de},{:onclick => "this.href=this.href+'/'+window.location.hash" })%>
            </div>
            <div class="col-md-4 col-xs-4 text-right hidden-xs hidden-sm">
              <%= link_to t('misc.titles.menus.terms_and_privacy.title'), terms_path %>
            </div>
          </div>
        </p>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="../../assets/js/docs.min.js"></script>-->
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?sensor=false">
    </script>
    <%= javascript_include_tag "application" %>
    <%= yield :script %>
    <%if I18n.locale.to_s === "de"%>
        <%= javascript_include_tag "vendor/angular-locale_de-de" %>
    <%end%>
    <%
    @translator = I18n.backend
    @translator.load_translations
    @translations ||= @translator.send(:translations)[I18n.locale][:javascript]
    %>
    <script type="text/javascript">
      var locale = "<%=I18n.locale.to_s%>";
      window.I18n = <%= @translations.to_json.html_safe %>;

      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-48728866-2', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>

app/views/layouts/mail_layout.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Your Message Subject or Title</title>
    <style type="text/css">

        /***********
        Originally based on The MailChimp Reset from Fabio Carneiro, MailChimp User Experience Design
        More info and templates on Github: https://github.com/mailchimp/Email-Blueprints
        http://www.mailchimp.com &amp; http://www.fabio-carneiro.com

        INLINE: Yes.
        ***********/
        /* Client-specific Styles */
        #outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
        body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
        /* Prevent Webkit and Windows Mobile platforms from changing default font sizes, while not breaking desktop design. */
        .ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
        .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;} /* Force Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */
        #backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
        /* End reset */

        /* Some sensible defaults for images
        1. "-ms-interpolation-mode: bicubic" works to help ie properly resize images in IE. (if you are resizing them using the width and height attributes)
        2. "border:none" removes border when linking images.
        3. Updated the common Gmail/Hotmail image display fix: Gmail and Hotmail unwantedly adds in an extra space below images when using non IE browsers. You may not always want all of your images to be block elements. Apply the "image_fix" class to any image you need to fix.

        Bring inline: Yes.
        */
        img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}
        a img {border:none;}
        .image_fix {display:block;}

        /** Yahoo paragraph fix: removes the proper spacing or the paragraph (p) tag. To correct we set the top/bottom margin to 1em in the head of the document. Simple fix with little effect on other styling. NOTE: It is also common to use two breaks instead of the paragraph tag but I think this way is cleaner and more semantic. NOTE: This example recommends 1em. More info on setting web defaults: http://www.w3.org/TR/CSS21/sample.html or http://meiert.com/en/blog/20070922/user-agent-style-sheets/

        Bring inline: Yes.
        **/
        p {margin: 1em 0;}

        /** Hotmail header color reset: Hotmail replaces your header color styles with a green color on H2, H3, H4, H5, and H6 tags. In this example, the color is reset to black for a non-linked header, blue for a linked header, red for an active header (limited support), and purple for a visited header (limited support).  Replace with your choice of color. The !important is really what is overriding Hotmail's styling. Hotmail also sets the H1 and H2 tags to the same size.

        Bring inline: Yes.
        **/
        h1, h2, h3, h4, h5, h6 {color: black !important;}

        h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}

        h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
            color: red !important; /* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. */
         }

        h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
            color: purple !important; /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
        }

        /** Outlook 07, 10 Padding issue: These "newer" versions of Outlook add some padding around table cells potentially throwing off your perfectly pixeled table.  The issue can cause added space and also throw off borders completely.  Use this fix in your header or inline to safely fix your table woes.

        More info: http://www.ianhoar.com/2008/04/29/outlook-2007-borders-and-1px-padding-on-table-cells/
        http://www.campaignmonitor.com/blog/post/3392/1px-borders-padding-on-table-cells-in-outlook-07/

        H/T @edmelly

        Bring inline: No.
        **/
        table td {border-collapse: collapse;}

        /** Remove spacing around Outlook 07, 10 tables

        More info : http://www.campaignmonitor.com/blog/post/3694/removing-spacing-from-around-tables-in-outlook-2007-and-2010/

        Bring inline: Yes
        **/
        table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }

        /* Styling your links has become much simpler with the new Yahoo.  In fact, it falls in line with the main credo of styling in email, bring your styles inline.  Your link colors will be uniform across clients when brought inline.

        Bring inline: Yes. */
        a {color: orange;}

        /* Or to go the gold star route...
        a:link { color: orange; }
        a:visited { color: blue; }
        a:hover { color: green; }
        */

        /***************************************************
        ****************************************************
        MOBILE TARGETING

        Use @media queries with care.  You should not bring these styles inline -- so it's recommended to apply them AFTER you bring the other stlying inline.

        Note: test carefully with Yahoo.
        Note 2: Don't bring anything below this line inline.
        ****************************************************
        ***************************************************/

        /* NOTE: To properly use @media queries and play nice with yahoo mail, use attribute selectors in place of class, id declarations.
        table[class=classname]
        Read more: http://www.campaignmonitor.com/blog/post/3457/media-query-issues-in-yahoo-mail-mobile-email/
        */
        @media only screen and (max-device-width: 480px) {

            /* A nice and clean way to target phone numbers you want clickable and avoid a mobile phone from linking other numbers that look like, but are not phone numbers.  Use these two blocks of code to "unstyle" any numbers that may be linked.  The second block gives you a class to apply with a span tag to the numbers you would like linked and styled.

            Inspired by Campaign Monitor's article on using phone numbers in email: http://www.campaignmonitor.com/blog/post/3571/using-phone-numbers-in-html-email/.

            Step 1 (Step 2: line 224)
            */
            a[href^="tel"], a[href^="sms"] {
                        text-decoration: none;
                        color: black; /* or whatever your want */
                        pointer-events: none;
                        cursor: default;
                    }

            .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
                        text-decoration: default;
                        color: orange !important; /* or whatever your want */
                        pointer-events: auto;
                        cursor: default;
                    }
        }

        /* More Specific Targeting */

        @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
            /* You guessed it, ipad (tablets, smaller screens, etc) */

            /* Step 1a: Repeating for the iPad */
            a[href^="tel"], a[href^="sms"] {
                        text-decoration: none;
                        color: blue; /* or whatever your want */
                        pointer-events: none;
                        cursor: default;
                    }

            .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
                        text-decoration: default;
                        color: orange !important;
                        pointer-events: auto;
                        cursor: default;
                    }
        }

        @media only screen and (-webkit-min-device-pixel-ratio: 2) {
            /* Put your iPhone 4g styles in here */
        }

        /* Following Android targeting from:
        http://developer.android.com/guide/webapps/targeting.html
        http://pugetworks.com/2011/04/css-media-queries-for-targeting-different-mobile-devices/  */
        @media only screen and (-webkit-device-pixel-ratio:.75){
            /* Put CSS for low density (ldpi) Android layouts in here */
        }
        @media only screen and (-webkit-device-pixel-ratio:1){
            /* Put CSS for medium density (mdpi) Android layouts in here */
        }
        @media only screen and (-webkit-device-pixel-ratio:1.5){
            /* Put CSS for high density (hdpi) Android layouts in here */
        }
        /* end Android targeting */
    </style>

    <!-- Targeting Windows Mobile -->
    <!--[if IEMobile 7]>
    <style type="text/css">

    </style>
    <![endif]-->

    <!-- ***********************************************
    ****************************************************
    END MOBILE TARGETING
    ****************************************************
    ************************************************ -->

    <!--[if gte mso 9]>
    <style>
        /* Target Outlook 2007 and 2010 */
    </style>
    <![endif]-->
</head>
<body>
    <!-- Wrapper/Container Table: Use a wrapper table to control the width and the background color consistently of your email. Use this approach instead of setting attributes on the body tag. -->
    <table cellpadding="0" cellspacing="0" border="0" id="backgroundTable">
    <tr>
        <td>

        <!-- Tables are the most common way to format your email consistently. Set your table widths inside cells and in most cases reset cellpadding, cellspacing, and border to zero. Use nested tables as a way to space effectively in your message. -->
        <table cellpadding="0" cellspacing="0" border="0" align="center">
            <tr>
                <td width="500" valign="top"><%= image_tag("flatman_logo.png", width: 60) %></td>
            </tr>
            <tr>
                <td width="500" valign="top">
                    <%=yield%>
                    <p><%= t('.complimentary_close') %></p>
                </td>
            </tr>
            <tr>
                <td width="500" valign="top">&copy; flatman <%= Time.now.year %></td>
            </tr>
        </table>

        <!-- End example table -->

        </td>
    </tr>
    </table>
    <!-- End of wrapper table -->
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, height=device-height,  initial-scale=1.0, user-scalable=no, user-scalable=0, maximum-scale=1"/>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : t('.default_description') %>">
    <meta name="robots" content="<%= yield :robots %>">
    <meta name="author" content="">
    <meta name="google-site-verification" content="24dGcQyKurRHX8RcO9sXp5pB-LqGotGHMVUM-U3YsgU" />
    <%= favicon_link_tag 'favicon.ico' %>

    <title>FlatMan<%= " » " + h(yield(:title)) if content_for?(:title) %></title>
    <%= stylesheet_link_tag "welcome", media: "all"%>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" id="trigger-overlay">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= welcome_url %>#flatman">
            <img src="<%= image_path( 'flatman_logo_border_30.png' ) %>" alt="Flatman" />
            <span class="hidden-xs"><%= t( ".navbar.flatman" ) %></span>
          </a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= welcome_url %>#flatman-contact"><%= t( ".navbar.contact" ) %></a></li>
            <li><a href="<%= signin_url %>"><%= t( ".navbar.login" ) %></a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="overlay overlay-hugeinc">
      <button type="button" class="overlay-close">
        <span class="fa fa-times fa-2x"></span>
      </button>
      <nav>
        <ul>
          <li><a href="<%= welcome_url %>#flatman"><img src="<%= image_path( 'flatman_logo_153x100.png' ) %>" alt="Flatman" /></a></li>
          <li><a href="<%= welcome_url %>#flatman-contact"><%= t( ".navbar.contact" ) %></a></li>
          <li><a href="<%= signin_url %>"><%= t( ".navbar.login" ) %></a></li>
        </ul>
      </nav>
    </div>
    
    <div id="pagepiling">
      
      <%= yield %>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "welcome" %>
    <%= yield( :content_script ) %>
    <script type="text/javascript">
      (function() {
        var triggerBttn = $( '#trigger-overlay' ),
            overlay     = $( 'div.overlay' ),
            closeBttn   = overlay.find( 'button.overlay-close' );

        function toggleOverlay() {
          overlay.fadeToggle();
        }

        triggerBttn.click( toggleOverlay );
        closeBttn.click( toggleOverlay );
      })();
    </script>
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-48728866-2', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>